apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/<your-username>/<your-repo>.git
    targetRevision: HEAD
    path: jenkins
    helm:
      chart: jenkins
      repo: https://charts.jenkins.io
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
